### ISSUE TITLE
Monitoring Unisphere Central for SC Series

### ISSUE THREAD

**Issue by jayscovill** [jiuka/checkmk_dell_storage#3]
Hi there, am trying to you use your plugin to monitor a Dell SC5020.  I stood up a Unisphere Central SC Series instance and added the SC5020 to it and am able to manage the SAN.

I have added the Unisphere Central VM as a host in CheckMK and set it to "Configured API Integration, no Checkmk Agent"

I then configured the plugin with a user in Unisphere Central and the following URL:

https://unisphere.domain.com:3033/api/rest/

I've also targeted the integration to the Unisphere Central host.

When I do a connection test it appears to be authenticating to the API but only returns the following info:

<<<check_mk>>>
Version: 20.1.1.716
AgentOS: EnterpriseManager
<<<dell_storage_agent:sep(59)>>>
0;EnterpriseManager;20.1.1.716;0.06640505790710449;2;

The Service configuration only shows the following services to monitor:

State        Service                   Status detail
 OK           Dell Storage API     Enterprise Manager v20.1.1.716

Is this designed to work with Unisphere Central and am I configuring it correctly?

Cheers!

**Comment by jiuka** [comment]
Hi @jayscovill

I use it with Unisphere Central/Enterprise Manager but not yet in version 20. And we have a SC5020 integrated as well. So this should work if it is not a version incompatibility. The special agent reports that it only made 2 requests to the api. This should be the login and then get the list of storage centers. If the List of storage centers is empty this would explain this behavior. If you login with the same user in the web interface of the (https://unisphere.domain.com:3033/ui/storage/storageCenters) do you get a list of storage centers?

Regards Marius

**Comment by jayscovill** [comment]
Hi,

Ok, I realize that the first problem here is that I didn't have a Storage Center mapped to the user I created for monitoring (Reporter access).

Now that I've mapped a Storage Center to it the connection test does query the list  and returns and returns the list of services such as controllers, etc.  However when I do a full services scan it's still only showing the state of the API but no other services.

So it looks like I'm still doing something wrong.

**Comment by jiuka** [comment]
Hi @jayscovill 

Not comes the piggyback magic. The server with the Unisphere Central only gets the one check reporting if the agent is running correctly. The other checks get assigned to other hosts. You either need to create these hosts manually or use the dynamic host configuration https://docs.checkmk.com/latest/en/dcd.html feature. In the agent output you find all the hosts getting piggyback data as `<<<<NAME>>>>` lines.

Regards Marius

**Comment by jayscovill** [comment]
Ok, I do have the Storage Center for the SAN set up as a host as I'm currently monitoring it via SNMP.  And the Agent data being returned during the connection test for the Unisphere Central host is listing the SAN Storage Center host.

If I'm understanding the piggyback mechanism correctly if I have the SAN storage center added as a host with the same name that is being returned by the agent it should automatically add the data to the SAN storage center?  That's not happening or nor is it if I force the piggyback option on the SAN host entry.  But I'm very new to CheckMK so my understanding could be flawed.

**Comment by jayscovill** [comment]
I noticed that the agent for the Unisphere Central is returning:

Version: 20.1.1.716
AgentOS: EnterpriseManager
<<<<sandomaincom>>>>
<<<dell_storage_center:sep(59)>>>
san.domain.com;Up;;Sc5000Series;7.4.21.4;G7M08B3;369598;0;2;38;0;49;0;5;7
<<<dell_storage_controller:sep(59)>>>
Bottom Controller;Up;;2021-04-18T08:50:39-04:00;False;Sc5020;7.4.21.4;G7M08B3;352-887-429-27;369599

Could it be that the piggyback data is trying to match "sandomaincom" with a valid host when the actual hostname is san.domain.com?  Is it just a matter of doing a hostname translation for piggyback hostst to match "sandomaincom" to "san.domain.com"?
